### ISSUE TITLE
lib assumes basePath is 'app'

### ISSUE THREAD

**Issue by younes0** [xinax/laravel-gettext#14]
I overrided default laravel paths, which is fine but your library still adds the `/app` path :
in FileSystem.php, echoing the basepath:
```php
public function __construct(Config $config, $basePath, $storagePath)
{
    echo($basePath);
}
 ```
 gives me `/www/yskel/application//app`  (`application` is laravel basepath)

**Comment by shaggyz** [comment]
Hey there!, yes, it was a bad idea to hardcode app_dir in the Laravel 5 upgrade. A new version with this fix will be released soon. The package service provider must be modified in order to make portable (again) the applications. This bug affects only 2.x / Laravel 5 projects.

Thanks!

**Comment by shaggyz** [comment]
Hi, I think is not a laravel-gettext issue. The service provide code is:

```php
...
$fileSystem = new FileSystem($configuration->get(), app_path(), storage_path());
...
```
Base-path is taken from the laravel helpers which is fine. I never tried to overload the laravel default paths, but I think this helper function must return values from **bootstrap/paths.php** or similar.

**Comment by canfiax** [comment]
I have same error I guess

**Comment by canfiax** [comment]
I fixed the issue! I simply created the dir "lang" in my /app/ dir. 

![image](https://cloud.githubusercontent.com/assets/3786627/6473936/2f2e8f18-c1fd-11e4-993a-da9e50bca7c7.png)

**Comment by younes0** [comment]
@shaggyz you're right, sorry for any inconvenience but I still encounter problems, I guess that lib assumes that lang is App's folder (which in my case is not): I suggest using \App::langPath() to define the lang folder

**Comment by shaggyz** [comment]
Hi @younes0, no problem! :+1: . Let's fix it. 

```php
"/www/yskel/application//../application/lang/i18n" //  dump on Filesystem.php:200
```
It's fine, laravel is returning your custom application path (In this package all paths are relative to app_path() in order to be portable)

So, you have the code in */www/yskel/application* and translations are in */www/yskel/data/lang*.

If you change the *translations-path* configuration value from *../resources/lang* to **../data/lang** should work fine.

```php
    /**
     * Base translation directory path (don't use trailing slash)
     */
    'translations-path' => '../data/lang', // /config/laravel-gettext.php:35
```

**Comment by younes0** [comment]
Okay everything works fine, the thing is I had manually created the i18n folder so I was getting this error: 'www/yskel/vendor/xinax/laravel-gettext/src/Xinax/LaravelGettext/FileSystem.php:200 - mkdir(): File exists' . I suggest to make a human friendly error such as "Files are already created". I can make a PR.

The other thing is that I had specified one locale in supported-locales which is also the default locale which in this case, the lib doesn't create PO files. It might be an anti-pattern, but I tend to also create default locale PO file in order to easily upgrade the copywriting without having to touch the php/blade files.

**Comment by shaggyz** [comment]
Well, I'd appreciate your PR. You need to set at least two languages, the .PO files are generated for the *second* one. Is to be supposed that all strings (on source code) are written on *first* language.

> It might be slightly dirty, but I tend to also create default locale PO file in order to easily upgrade the copywriting without having to touch the php/blade files 

Maybe the work-flow of this package doesn't fit with your project's needs. The only way to do this with laravel-gettext is: add a second different locale without translations and only maintain the good one. 

It's your choice :D.

**Comment by younes0** [comment]
I manually created the default language PO, and my config is :
```php
'locale' => 'fr_FR',
'supported-locales' => ['en_US', 'fr_FR'],	
```
the lib does read the default locale PO file, this is what I wanted. 

What's great with this lib is that It takes in account original view blade files which I couldn't figure out with my previous home-made solution or with other gettext packages: I had to compile blade view files, and setup POedit to look up in the compiled files.

Cheers.
